### ISSUE TITLE
Black hole object breaks ||= assignment

### ISSUE THREAD

**Issue by brauliobo** [arturoherrero/ofstruct#29]
See the example below
```
3.1.2 :001 > require 'ofstruct'; os=OpenFastStruct.new; os.v ||= 5
 => #<OpenFastStruct> 
3.1.2 :002 > os.v
 => #<OpenFastStruct>
```

**Comment by arturoherrero** [comment]
@brauliobo, I see you are testing the gem inside out!

This is failing, because that use case is not implemented. I only implemented the assignment:
https://github.com/arturoherrero/ofstruct/blob/0.3.0/lib/ofstruct.rb#L45

I'm not sure how we can get benefit from memoizing some values inside `OpenFastStruct`. Can you please expand on the reason behind this with a more complex example?

**Comment by brauliobo** [comment]
Basically, I'm using Hashie::Mash in any hash-like structure across large codebases. For instance, a message in AWS SQS comes and gets transformed into it. It might have some values missing, so the `||=` operator is useful.

**Comment by arturoherrero** [comment]
@brauliobo I think we cannot use `||=` because the operator is not a method, it's a syntax sugar for `var = var || value`, and `method_missing` only will be called when a method is not found in the class.

**Comment by arturoherrero** [comment]
I'm closing this as won't do as explained https://github.com/arturoherrero/ofstruct/issues/29#issuecomment-1404866268.
